### ISSUE TITLE
[Feature Request] Hide emule seeding items

### ISSUE THREAD

**Issue by acorderob** [Lemutar/Synoloader#26]
Emule items that are in the seeding state are distracting because there can be so many of them. They also do not show correctly because some informacion is missing and sizes and percent shows as NaN.

It would be nice to have an option to hide them in the list. And in case of showing them do not show invalid information.

Thanks.

**Comment by noplanman** [comment]
@acorderob Thanks for the feedback!
We'll definitely consider an option to filter the visible tasks, good idea.

Regarding the missing information you're talking about:
Do you also get NaN when downloading a file?
I'm new to Emule and have now downloaded a file to see what happens. I don't see any problems when downloading. All values are shown correctly, just like a torrent download.

Could you give me any tips on how I could test the seeding? How do I get somebody to download my file, so that I get the seeding status? :confused: 

Thanks!

**Comment by acorderob** [comment]
The problem is only seen when the download ends and you start seeding. To see it you just need to download something recent. I attach an image of how it is seen, and this is the JSON bit:

{
"additional": {
    "transfer": {
        "size_downloaded": "0",
        "size_uploaded": "314729179",
        "speed_download": 0,
        "speed_upload": 7314
    }
},
"id": "emuleUpload_1098",
"size": "0",
"status": "seeding",
"title": "Gotham 1x07 El paraguas del pingüino [HDiT Dvb spanish-english][ava lavinia - ForosFreaky.eU-GrupoHD].avi",
"type": "emule",
"username": "admin"
},

It seems that when status is set to "seeding" the size is reset (maybe a bug in the API) and the username changes to "admin" even if the original user was different.

![seeding_error](https://cloud.githubusercontent.com/assets/6293935/12185741/4375b48a-b59d-11e5-8c18-ec76c4f51831.png)

**Comment by noplanman** [comment]
Ok, thanks for the info.
What DSM are you on?

**Comment by acorderob** [comment]
DSM 5.2-5644
DownloadStation 3.5-2968


-------------------------------------------------------
Antonio Cordero Balcázar
antonio.cordero@gmail.com
