### ISSUE TITLE
Failed using Firefox 44 (64bits) / Download Station 3.5-2970

### ISSUE THREAD

**Issue by zorromymy** [Lemutar/Synoloader#33]
I don't know if it is related to the lastest Download Station update or the Firefox 44 (64bits) , but synoloader seems now unable to capture the links.

When the synoloader is enabled, it prevent the internal download function of firefox to work!
If I click a link for download, Firefox popup the dialogbox. But OK button is without effect. The only way to close the dialog is "cancel"
"Internal Firefox download" works again after disabling synoloader 

Firefox 44 (64bits)
Download Station 3.5-2970
Windows 10

Regards,

Laurent

**Comment by azevedo-manuel** [comment]
Yes, noticed the same on both Mac and Windows versions.

**Comment by pschonmann** [comment]
With Synolader im not able to download any file. Firefox dialog about downloading appear i click on download (not with synoloader) and then just clicking on OK, nothing happens, even dialog wont close ( only cancel or X )

**Comment by noplanman** [comment]
@Dimas-sc, @zorromymy, @azevedo-manuel, @pschonmann and all others that are experiencing this issue.
You can get a temporary fixed version of Synoloader here: https://github.com/noplanman/Synoloader/raw/firefox-44-hotfix/bin/Synoloader.xpi

Just uninstall the current version from your Firefox, download the file above and install it by drag-dropping it into your Firefox window.
Alternatively you can select `Install Add-on from file...` on the Add-ons window.

We'll try to get this fixed for the next official version, sorry for the inconvenience... :confused:

(This fix also applies to issue #30)

@Lemutar, we really need to get this fixed in the official version, because it will break for everyone who updates to Firefox 44!

**Comment by pschonmann** [comment]
Not working for me.

**Comment by noplanman** [comment]
What operating system are you on? I've tested this on OSX Mavericks and Windows 7, no problems.

Did the plugin install successfully or did you get the "Can't install the Add-on because it's not signed." error?
To allow non-signed add-ons, go to `about:config` in the address bar. Then search for the entry `xpinstall.signatures.required` and set it to `false`.
Then try the installation again.

**Comment by pschonmann** [comment]
W10x64 FF is 32bit
signatures off.

**Comment by noplanman** [comment]
Other people have had issues with Windows before.
Try following these steps exactly: https://github.com/Lemutar/Synoloader/issues/18#issuecomment-170550720
Important is to restart again at the end. I hope that fixes it.
This issue is still a mystery to me which desperately needs a solution.

Does this fix it for you?

**Comment by azevedo-manuel** [comment]
Hello @noplanman, I've installed it. Firefox on OS X El Capitain. Same behaviour. Still hijacks the save button.

**Comment by noplanman** [comment]
Oh man, you're right... Must have not updated properly when I was testing :confused: 
In that case I don't have a fix for now, so sorry.

Trying to figure it out, bear with me.
@Lemutar, would appreciate your assistance on this, reaching the limits of my Firefox Add-on knowledge :blush:

**Comment by zorromymy** [comment]
Hello, I've installed the patched version. (FF 64bits / Win10 64bits).
Same behaviour,  the download dialog box still fail.

**Comment by noplanman** [comment]
Ok guys, I think I've found the problem, could you please try again.
Same file, just re-download it to get the new version.

**Comment by azevedo-manuel** [comment]
Hi @noplanman, it works this time :)
Really hope you can patch the official version! Not very keen on running unsigned xpis :)
Thanks a lot! Nice job!

**Comment by noplanman** [comment]
@azevedo-manuel 
Absolutely! Hope to get this implemented officially soon.

Thanks for the patience while we're getting this sorted :blush:

**Comment by zorromymy** [comment]
Great!  Works for me too 
Thank you

**Comment by s0rk** [comment]
Yes, indeed. Works for me too. I experienced this problem earlier today, and I'm quite impressed to see a solution implemented so soon. Thanks a lot for this fix!
